### ISSUE TITLE
Editor. Reward ??? USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Core-WRIO-App#1]
Создать widget/core.htm для редактора. Он будет вызываться при нажатии на кнопку create в Plus либо из хаба к которому у пользователя есть доступ. Создать страницу
```
https://github.com/webRunes/Core-WRIO-App/blob/master/widget/create.htm
```
с редактором. Привязку к ней сделаем позже. Сперва разработать только для Article, остальные будут позже. Страница будет вызываться по ссылке
```
wrio.s3-website-us-east-1.amazonaws.com/Core-WRIO-App/widget/create.htm
```
Использовать http://bootstrap-wysiwyg.github.io/bootstrap3-wysiwyg/
В редакторе пока скрыть все кнопки кроме:
```
Heading
Normal text
```
```
Quote
```
```
Unordered list
```
```
Ordered list
```
```
Insert link
```

Текст внутри json-ld будет работать по принципам Markdown. Примеры разметки: https://guides.github.com/features/mastering-markdown/#examples

При парсинге json-ld если в "articleBody" встречается конструкция вида
```
* Здесь идет текст
```
система должна отображать такой текст из "articleBody" в виджете article в виде списка
```
<ul><li>...<li></ul>
```
В примере https://guides.github.com/features/mastering-markdown/#examples раздел "Emphasis" используются символы "*" и "_" для bold и italic, использовать только "*".
Аналогично для
```
1. Здесь идет текст
```
будет:
```
<ol><li>...<li></ol>
```
Обратить внимание на то, что символ должен идти первым в строке и с пробелом после символа, это важно, чтобы оставить возможность использовать символы и цифры и в тексте.

Специальным образом обрабатывать цитату пока не надо, просто сохранять в json-ld (в "articleBody") также как простой текст, разница лишь в том, что идет перед текстом символ ">" (см. выше пример https://guides.github.com/features/mastering-markdown/#examples в разделе "Headers & Quotes") перед ним.
```
> Здесь идет цитата
```
После нажатия на "Save" - вызывать окно сохранения на локальный диск и в соответствии тексту в редакторе сохранять html файл с автоматически сгенерированным json-ld внутри.

В помощь:
https://github.com/jbt/markdown-editor
он большой по размерам и нам неподходит, но, возможно, его код будет полезен при разработке в виде примера.

**Comment by AlexeyAnshakov** [comment]
Для ссылок применять markdown не нужно, они должны оставаться в "mention"

**Comment by AlexeyAnshakov** [comment]
it's working but i don't see controls because of wrong urls
>http://wrio.s3-website-us-east-1.amazonaws.com/Core-WRIO-App/widget/wrio.s3-website-us-east-1.amazonaws.com/Default-WRIO-Theme/css/bootstrap.min.css

**Comment by AlexeyAnshakov** [comment]
Редактор отображается, но save не работает если просто написать пару слов. При вставке ссылки, после нажатия на нее и затем на cancel - popup пропадает, но темный экран остается. Кнопку edit html надо убрать.

**Comment by wall2003** [comment]
При вставке ссылки, после нажатия на нее и затем на cancel - popup пропадает, но темный экран остается.
проверил в IE, FF, Chrome - во всех браузерах работает корректно (логика родная, я ни каких изменений не вносил)

**Comment by wall2003** [comment]
save не работает если просто написать пару слов.
нашел пару ошибок

**Comment by wall2003** [comment]
Кнопку edit html надо убрать - убрал
