### ISSUE TITLE
Posts list

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Core-WRIO-App#465]
При создании первого поста параллельно создавать list.html в корне, где хранить список всех постов пользователя. Отображать его содержимое в дропдауне на странице редактора сразу под синей плашкой -- UI я поправлю позже сам. При выборе из списка переходить на соответствующую страницу в режим редактирования.

**Comment by spirinvladimir** [comment]
@AlexeyAnshakov this issue is done.
