### ISSUE TITLE
Access for widget

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Core-WRIO-App#5]
Please set deploy settings for
https://travis-ci.org/webRunes/Core-WRIO-App

**Comment by AlexeyAnshakov** [comment]
At this moment only widget dir is deployed. Please open
>http://wrio.s3-website-us-east-1.amazonaws.com/Core-WRIO-App/

not only
>http://wrio.s3-website-us-east-1.amazonaws.com/Core-WRIO-App/widget/

**Comment by umairadeeb** [comment]
This is done against https://github.com/webRunes/Core-WRIO-App/pull/10
